services:
  - type: web
    name: event-streaming-gateway
    runtime: python
    plan: free
    buildCommand: pip install -r services/gateway/requirements.txt
    startCommand: python -m uvicorn services.gateway.app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: prod
      - key: MESSAGE_BACKEND
        value: kafka
      - key: CORE_PROCESS_URL
        value: https://event-streaming-core.onrender.com/process
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: REPLACE_ME
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_SASL_USERNAME
        value: REPLACE_ME
      - key: KAFKA_SASL_PASSWORD
        value: REPLACE_ME
      - key: TRACING_ENABLED
        value: "false"

  - type: web
    name: event-streaming-core
    runtime: python
    plan: free
    buildCommand: pip install -r services/core/requirements.txt
    startCommand: python -m uvicorn services.core.app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: prod
      - key: MESSAGE_BACKEND
        value: kafka
      - key: CONSUMER_GROUP
        value: core-consumer-group
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: REPLACE_ME
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_SASL_USERNAME
        value: REPLACE_ME
      - key: KAFKA_SASL_PASSWORD
        value: REPLACE_ME
      - key: TRACING_ENABLED
        value: "false"

  - type: web
    name: event-streaming-replay
    runtime: python
    plan: free
    buildCommand: pip install -r services/replay/requirements.txt
    startCommand: python -m uvicorn services.replay.app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: prod
      - key: MESSAGE_BACKEND
        value: kafka
      - key: DEFAULT_REPLAY_TARGET
        value: https://event-streaming-gateway.onrender.com/ingest
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: REPLACE_ME
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_SASL_USERNAME
        value: REPLACE_ME
      - key: KAFKA_SASL_PASSWORD
        value: REPLACE_ME
      - key: TRACING_ENABLED
        value: "false"