services:
  - type: web
    name: event-streaming-gateway
    runtime: python
    plan: free
    buildCommand: pip install -r services/gateway/requirements.txt
    startCommand: python -m uvicorn services.gateway.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: prod
      - key: MESSAGE_BACKEND
        value: filesystem
      - key: CORE_PROCESS_URL
        value: https://event-streaming-core.onrender.com/process
      - key: TRACING_ENABLED
        value: "false"

  - type: web
    name: event-streaming-core
    runtime: python
    plan: free
    buildCommand: pip install -r services/core/requirements.txt
    startCommand: python -m uvicorn services.core.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: prod
      - key: MESSAGE_BACKEND
        value: filesystem
      - key: TRACING_ENABLED
        value: "false"

  - type: web
    name: event-streaming-replay
    runtime: python
    plan: free
    buildCommand: pip install -r services/replay/requirements.txt
    startCommand: python -m uvicorn services.replay.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: prod
      - key: MESSAGE_BACKEND
        value: filesystem
      - key: DEFAULT_REPLAY_TARGET
        value: https://event-streaming-gateway.onrender.com/ingest
      - key: TRACING_ENABLED
        value: "false"